# Generated by Django 5.2.11 on 2026-02-04 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the incident', primary_key=True, serialize=False)),
                ('reporter_name', models.CharField(help_text='Name of the person who reported the incident', max_length=255)),
                ('reporter_phone', models.CharField(blank=True, help_text='Contact phone number of the reporter', max_length=20, null=True)),
                ('lat', models.DecimalField(decimal_places=6, help_text='Latitude coordinate of the incident', max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, help_text='Longitude coordinate of the incident', max_digits=9)),
                ('address', models.TextField(help_text='Human-readable address of the incident')),
                ('description', models.TextField(help_text='Detailed description of the fire incident')),
                ('status', models.CharField(choices=[('new', 'New'), ('enroute', 'En Route'), ('arrived', 'Arrived'), ('fighting', 'Fighting Fire'), ('extinguished', 'Extinguished'), ('closed', 'Closed')], default='new', help_text='Current status of the incident', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the incident was reported')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the incident was last updated')),
                ('reporter', models.ForeignKey(blank=True, help_text='User who reported the incident (null if anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the photo', primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Uploaded incident photo', upload_to='incident_photos/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the photo was uploaded')),
                ('incident', models.ForeignKey(help_text='The incident this photo belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'Incident Photo',
                'verbose_name_plural': 'Incident Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the status update', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('enroute', 'En Route'), ('arrived', 'Arrived'), ('fighting', 'Fighting Fire'), ('extinguished', 'Extinguished'), ('closed', 'Closed')], help_text='New status of the incident', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Optional notes about the status change (e.g., 'Team Alpha dispatched')", null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this status update was created')),
                ('incident', models.ForeignKey(help_text='The incident this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='incidents.incident')),
                ('updated_by', models.ForeignKey(help_text='User who made this status update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Status Update',
                'verbose_name_plural': 'Status Updates',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['-created_at'], name='incidents_i_created_c4c91a_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_i_status_9a4f12_idx'),
        ),
        migrations.AddIndex(
            model_name='statusupdate',
            index=models.Index(fields=['-timestamp'], name='incidents_s_timesta_3c5178_idx'),
        ),
    ]
